services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  testdb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres_testdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    ports:
      - '5433:5432'
    volumes:
      - testdb_data:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
  testdb_data:
    driver: local